### ISSUE TITLE
Add variable-substitution supports

### ISSUE THREAD

**Issue by gologic-ben** [emerald-squad/cf-zero-downtime-resource#1]
Is it possible to add variable-substitution supports as described in documentation: 
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#variable-substitution

**Comment by ukabu** [comment]
While it may not be a complete solution for this use case, version 0.5.2 now support [inline manifest](https://github.com/emerald-squad/cf-zero-downtime-resource#inline-manifest). This mean you can use Concourse variable to achieve the same result when you set your pipeline.

**Comment by xNok** [comment]
Variable substitution works by adding --vars-file.
cf push foo-app -f ~/workspace/var_manifest.yml **--vars-file ~/workspace/vars.yml**

You could update you cf api `cf.js`, so that it support this feature. (line 126 when you build you command line)
