### ISSUE TITLE
spring project build failed

### ISSUE THREAD

**Issue by dheeraj002** [emerald-squad/cf-zero-downtime-resource#4]
[manifest.txt](https://github.com/emerald-squad/cf-zero-downtime-resource/files/2198894/manifest.txt)

I am using concourse pipeline to build a simple java application but looks like the resource type is not able to get into my manifest.yml correctly ..giving below errors:-

{ YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:754:13)
    at writeBlockMapping (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
    at writeNode (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
    at writeBlockSequence (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:520:9)
    at writeNode (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:738:9)
    at writeBlockMapping (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:633:10)
    at writeNode (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:726:9)
    at dump (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:815:7)
    at Object.safeDump (/opt/resource/node_modules/js-yaml/lib/js-yaml/dumper.js:821:10)
    at cmd (/opt/resource/out.js:92:43)
  name: 'YAMLException',
  reason: 'unacceptable kind of an object to dump [object Undefined]', 
  mark: undefined,
  message: 'unacceptable kind of an object to dump [object Undefined]' }

below is my manifest file:-

applications:
- name: test-Server
  health-check-http-endpoint: /health
  health-check-type: http
  path: target/test-service-0.0.1-SNAPSHOT.jar
  memory: 1024M
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
[pipeline.txt](https://github.com/emerald-squad/cf-zero-downtime-resource/files/2198901/pipeline.txt)

**Comment by ukabu** [comment]
Thanks for reporting this.
Can you attach the pipeline.yml (beeing careful not to include any sensitive information).
For the manifest, can you either attach it too or use the code formatting (https://guides.github.com/features/mastering-markdown/) so we can see the proper indentation.

**Comment by dheeraj002** [comment]
have attached both the files -
manifest.txt
pipeline.txt


you can convert them back to yml extensions.
Thanks.

**Comment by ukabu** [comment]
The issue is that you did not specify the `name` parameter in the `put`.
```
    - put: PWS
      params:
       name: test-Gateway-Server
       manifest: gateway-service/gateway-service/manifest.yml
       path: build-output/gateway-service-0.0.1-SNAPSHOT.jar
```
The name does not have to be the same as the one in the manifest (it will overwrite it), the application will be deployed with that name regardless of the name in the manifest.

We should better guard for this (and actually validate the required parameters as per the documentation), I will open an issue to fix this.

**Comment by dheeraj002** [comment]
i tried to put name  but still the issue is same. 
Can u please share some working code snippet.

**Comment by ukabu** [comment]
Are you sure you did a `set-pipeline` after modifying the pipeline?

Also please note the that `skip_cert_check: true` isn't implmented right now.

Can you attach your updated pipeline and manifest.

**Comment by ukabu** [comment]
also make sure your indentation is consistent (I recommend you always use 2 spaces).
