### ISSUE TITLE
Venerable versions deleted upon multiple deployment failures

### ISSUE THREAD

**Issue by fortioli** [emerald-squad/cf-zero-downtime-resource#6]
**Describe the bug**
Venerable versions are deleted upon multiple deploy failures, leaving only a non-running failed version.

**To Reproduce**
1. Have an app with a version already running.
2. Deploy a version that fails its deploy: the previously running version is renamed *appname*-venerable and the new one is renamed *appname*-failed. The venerable version starts running again to ensure zero downtime.
3. Deploy the same failing version, or any other version that will fail.
4. The new failing version is renamed *appname*-failed but the old *appname*-venerable has been deleted.
5. There is no app running.

**Expected behavior**
The old "venerable" version should still be available and not deleted.

**Additional context**
This probably comes from the fact that when a deployment starts, the currently running app is renamed *appname*-venerable and every other version with venerable is deleted. There should probably be a check to see if the currently running version IS venerable before deleting, or simply rename venerable to simply *appname* if the deployment failed.

**Comment by ukabu** [comment]
Can you provide the logs of the failed deploys.
The deploiement process is like this:
1. If `app-venerable` exists, delete it,
2. rename `app` to `app-venerable,
3. deploy new version as `app`
4. if deploy fails, rename `app` to `app-failed`, rename `app-venerable` to `app`

So you should always have your `app` deployed (unless it fails the first time you do it).

Maybe something went wrong when renaming `app-venerable` back to `app` if so I would like to know more about that failure.
