### ISSUE TITLE
Add support to deploy multiple apps

### ISSUE THREAD

**Issue by matbain** [emerald-squad/cf-zero-downtime-resource#8]
Hi,

As of today, it seems you only support a manifest file that deploys only one app.
However, when a project has multiple modules to deploy it can become quite painful to define and maintain in concourse a put command  for each single app to deploy.

Do you have any plan to support the case when a manifest is defines to deploy multiple apps ?

**Comment by ukabu** [comment]
We have no plan to support manifest with multiple apps. Zerodowntime deploys for multiple apps is an order of magniture more complex than one app at a time. Deploying multimodule apps with a single manifest is an anti-pattern in our opinion.
